services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
#    command: ["redis-server", "--appendonly", "yes"]
#    command: redis-server --requirepass redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
#      - HTTP_USER=${REDIS_USER}
#      - HTTP_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8082:8081"
    depends_on:
      - redis

volumes:
#  mysql:
#    driver: "local"
  redis:
    driver: "local"


#  mysql:
#    image: mysql:8
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=test_db
#    volumes:
#      - mysql:/var/lib/mysql
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    environment:
#      - PMA_HOST=mysql
#      - PMA_USER=root
#      - PMA_PASSWORD=root
#    ports:
#      - "8081:80"