services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true
        public: true

    Predis\Client:
      arguments:
        - '%env(DATABASE_URL)%'

    App\Infrastructure\Database\Redis\RedisClient:
      arguments:
        - '@Predis\Client'

